//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.uky.pf.model;

import java.util.UUID;

import com.hp.api.Id;
import com.hp.api.Transportable;
import com.hp.sdn.BaseModel;
import com.hp.sdn.auditlog.AuditLogEntry;
import com.hp.sdn.Model;

/**
 * Sample PathFollower domain model.
 */
public class PathFollower extends Model<PathFollower> {

    private static final long serialVersionUID = 7571309040451072286L;


    /*Important data structures go here. For instance the type of data you want to collect
     * and store in the controller */
    
    private String name;


}
