//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.uky.pf.api;

import java.util.UUID;

import com.uky.pf.model.PathFollower;
import com.hp.api.NotFoundException;

import com.hp.api.Id;

import java.util.Collection;

/**
 * Sample PathFollower service interface.
 */
public interface PathFollowerService {

	/* sergio: API signatures go here but you might not need any of them for PathFollower.
	 * They are usually to access the Manager via REST
	 *  
	 */

}
